-- Run this in your Supabase SQL Editor to apply the schema changes

-- 1. Create Project Budgets table (Replacing LocalStorage)
CREATE TABLE IF NOT EXISTS project_budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT NOT NULL,
  category_key TEXT NOT NULL, -- 'grey', 'finishing', 'contractors', 'misc'
  budget_amount NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(project_id, category_key)
);

-- Enable RLS
ALTER TABLE project_budgets ENABLE ROW LEVEL SECURITY;

-- Policy: Allow all access (Adjust if you have strict auth requirements)
CREATE POLICY "Enable all access for authenticated users" ON project_budgets
FOR ALL USING (true) WITH CHECK (true);

-- 2. Add Retention Amount to Payment Log
ALTER TABLE payment_log 
ADD COLUMN IF NOT EXISTS retention_amount NUMERIC DEFAULT 0;

-- 3. Ensure Material Purchase columns exist (in case they are missing)
ALTER TABLE material_purchases 
ADD COLUMN IF NOT EXISTS qty NUMERIC,
ADD COLUMN IF NOT EXISTS unit TEXT,
ADD COLUMN IF NOT EXISTS rate NUMERIC;
