-- Progress Entries Table (for AI-powered site progress tracking)
CREATE TABLE IF NOT EXISTS progress_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  image_base64 TEXT,
  ai_analysis TEXT,
  phase TEXT DEFAULT 'general',
  status TEXT DEFAULT 'in-progress',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE progress_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for authenticated users" ON progress_entries
FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_progress_project ON progress_entries(project_id);
CREATE INDEX IF NOT EXISTS idx_progress_created ON progress_entries(created_at DESC);
