-- ─────────────────────────────────────────────
-- 1. Storage RLS policies (buckets already created via API)
-- ─────────────────────────────────────────────

-- Allow public read on all three buckets
CREATE POLICY "Public read invoices" ON storage.objects
  FOR SELECT USING (bucket_id = 'invoices');

CREATE POLICY "Public read contractor-docs" ON storage.objects
  FOR SELECT USING (bucket_id = 'contractor-docs');

CREATE POLICY "Public read site-photos" ON storage.objects
  FOR SELECT USING (bucket_id = 'site-photos');

-- Allow anon insert/update/delete (app uses anon key; RLS is our only gate)
CREATE POLICY "Anon insert invoices" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'invoices');

CREATE POLICY "Anon update invoices" ON storage.objects
  FOR UPDATE USING (bucket_id = 'invoices');

CREATE POLICY "Anon delete invoices" ON storage.objects
  FOR DELETE USING (bucket_id = 'invoices');

CREATE POLICY "Anon insert contractor-docs" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'contractor-docs');

CREATE POLICY "Anon update contractor-docs" ON storage.objects
  FOR UPDATE USING (bucket_id = 'contractor-docs');

CREATE POLICY "Anon delete contractor-docs" ON storage.objects
  FOR DELETE USING (bucket_id = 'contractor-docs');

CREATE POLICY "Anon insert site-photos" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'site-photos');

CREATE POLICY "Anon update site-photos" ON storage.objects
  FOR UPDATE USING (bucket_id = 'site-photos');

CREATE POLICY "Anon delete site-photos" ON storage.objects
  FOR DELETE USING (bucket_id = 'site-photos');

-- ─────────────────────────────────────────────
-- 2. material_purchases — swap base64 → Storage URL
-- ─────────────────────────────────────────────
ALTER TABLE material_purchases
  ADD COLUMN IF NOT EXISTS invoice_url TEXT;

-- Keep invoice_data/invoice_name for backwards-compat during transition,
-- new entries will use invoice_url only.

-- ─────────────────────────────────────────────
-- 3. progress_entries — add storage URL column
-- ─────────────────────────────────────────────
ALTER TABLE progress_entries
  ADD COLUMN IF NOT EXISTS ai_phase TEXT,
  ADD COLUMN IF NOT EXISTS ai_quality TEXT,
  ADD COLUMN IF NOT EXISTS ai_progress_pct INTEGER,
  ADD COLUMN IF NOT EXISTS photo_url TEXT;

-- ─────────────────────────────────────────────
-- 4. contractor_schedules — new table
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS contractor_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contractor_id TEXT NOT NULL,        -- matches contractors.contractor_id
  project_id TEXT NOT NULL,
  milestone TEXT NOT NULL,            -- e.g. "Foundation Complete"
  amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  due_date DATE,
  paid_date DATE,
  status TEXT NOT NULL DEFAULT 'Pending', -- Pending | Paid | Overdue
  notes TEXT,
  doc_url TEXT,                       -- Supabase Storage URL for attached PDF/image
  doc_name TEXT,                      -- original filename
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

ALTER TABLE contractor_schedules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all on contractor_schedules" ON contractor_schedules
  FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_cs_contractor ON contractor_schedules(contractor_id);
CREATE INDEX IF NOT EXISTS idx_cs_project ON contractor_schedules(project_id);
